### ISSUE TITLE
Create a LICENSE file

### ISSUE THREAD

**Issue by shadowbq** [deajan/linuxscripts#3]
please license these scripts appropriately. I found the ddsplit to be useful on esxi as it had no split command.

**Comment by deajan** [comment]
Sure, done.
I'm quite curious, what exactly do you use ddsplit for on esxi ?

**Comment by shadowbq** [comment]
Also .. 
I ported it to sh as there is no bash.. (so I loose some things like pipefail, but it was useful). 

What did I use it for?
ESXi machines not managed under vsphere that had local storage with extremely large vmdk files (1-3TB disk files). I sliced them directly onto an external NFS mount during a migration off the ESXi physical machines.
